version: '3.4'

services:
  microservice.template.catalog.api:
    image: ${DOCKER_REGISTRY-}microservicetemplatecatalogapi
    build:
      context: .
      dockerfile: src/services/MicroService.Template.Catalog.Api/Dockerfile
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: catalogDB  
    ports:
      - "5442:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
